const certTypes = [
  'CLOUD COMPUTING',
  'CLOUD COMPUTING',
  'FULL STACK WEB',
  'ANDROID DEVELOPMENT',
  'ANDROID DEVELOPMENT',
  'ANDROID DEVELOPMENT',
  'ANDROID DEVELOPMENT',
  'BACKEND WEB',
  'CLOUD COMPUTING',
  'FRONTEND WEB',
  'JAVA',
  'JAVASCRIPT',
  'KOTLIN',
  'DATA ANALYST',
  'MACHINE LEARNING'
]
export default certTypes